# wrangler.toml
name = "gemini"
main = "src/index.ts"
compatibility_date = "2025-03-27"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./public"

[observability]
enabled = true

[[kv_namespaces]]
binding = "GEMINI_KEYS_KV"
id = "60432b2ef26944d69f1141440029ad3b"

[[kv_namespaces]]
binding = "WORKER_CONFIG_KV"
id = "60432b2ef26944d69f1141440029ad3b"

